# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - master

resources:
  - repo: self

variables:
  tag: "$(Build.BuildId)"

stages:
  - stage: Build
    displayName: Build Image Stage
    jobs:
      - job: Build
        displayName: Build Image Job
        pool:
          vmImage: "ubuntu-latest"
          steps:
            - task: Docker@2
              displayName: Build an Image
              inputs:
                containerRegistry: "hmzkv88 Dockerhub"
                repository: "hmzkv88/weatherapi:${tag}"
                command: "buildAndPush"
                Dockerfile: "**/Dockerfile"
                tags: |
                  $(tag)
  - stage: Provision
    displayName: "Terraform provisioning on Azure..."
    dependsOn: Build
    jobs:
      - job: Provision
        displayName: "Provisioning Container Instances"
        pool:
          vmImage: "ubuntu-latest"
        variables:
          - group: VG_TerraformServicePrincipal
        steps:
          - script: |
              set -e
              terraform init -input=false
              terraform apply -input=false -auto-approve
            name: "RunTerraform"
            displayName: "Run Terraform"
            env:
              TF_VAR_imagebuild: $(tag)
              ARM_CLIENT_ID: $(ARM_CLIENT_ID)
              ARM_TENANT_ID: $(ARM_TENANT_ID)
              ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
              ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
